name: OB screenshots + mailer (hourly IST)

on:
  # ───────────── 09:00–21:00 IST (03:30–15:30 UTC) ─────────────
  schedule:
    - cron: '30 3-15 * * *' # “:30 past” each hour 03-15 UTC
  workflow_dispatch: # manual Run-workflow button

jobs:
  mailer:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Python 3.10
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3️⃣ Headless Chrome *stable* (v125.x at the moment)
      # → matches Chromedriver shipped by undetected-chromedriver
      - name: Install headless Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable # ⚠️ pin to “stable”, **not** latest-canary

      # 4️⃣ pip install deps
      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5️⃣ run the mailer
      - name: Run mailer
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
        run: python main.py
