name: OB screenshots + mailer (hourly IST)

on:
  # ────────────────────────────────────────────────────────────────
  # Schedule:
  # • GitHub clocks are always UTC
  # • 09:00 IST = 03:30 UTC
  # • 21:00 IST = 15:30 UTC
  # • The line below fires at 30 min past each hour 03-15 UTC,
  #   i.e. 09:00, 10:00, … 21:00 IST
  # ────────────────────────────────────────────────────────────────
  schedule:
    - cron: '30 3-15 * * *'  # ↖ minute hour range day month weekday
  workflow_dispatch:         # manual “Run workflow” button in GitHub UI

jobs:
  mailer:
    runs-on: ubuntu-latest  # Use the latest stable Ubuntu runner

    steps:
      # 1️⃣ Grab the repo content
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Python 3.10
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3️⃣ Install headless Chrome + chromedriver
      - name: Install headless Chrome
        uses: browser-actions/setup-chrome@v1

      # 4️⃣ Install required Python dependencies
      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5️⃣ Run the main Python script with environment secrets
      - name: Run mailer
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}  # sender email address
          SMTP_PASS: ${{ secrets.SMTP_PASS }}  # 16-char Gmail App-Password
        run: python main.py
