name: Auto Mailer

on:
  schedule:
    # 09:30–20:30 IST, hourly
    - cron: '30 3-14 * * *'
  workflow_dispatch: # manual trigger

jobs:
  mailer:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Python deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Chrome + chromedriver
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip google-chrome-stable
        CHROME_VERSION=$(google-chrome-stable --version | grep -oP '\d+\.\d+\.\d+\.\d+')
        wget -q https://storage.googleapis.com/chrome-for-testing-public/${CHROME_VERSION}/linux64/chromedriver-linux64.zip -O /tmp/chromedriver.zip
        unzip -o /tmp/chromedriver.zip -d /tmp
        sudo mv /tmp/chromedriver-linux64/chromedriver /usr/bin/chromedriver
        sudo chmod +x /usr/bin/chromedriver

    - name: Write service‑account key
      env:
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      run: |
        echo "$GCP_SA_KEY" | grep -q '"type": "service_account"' || \
          (echo "Secret GCP_SA_KEY missing or base64‑encode it!" && exit 1)
        # decode if base64 or just write raw JSON
        if echo "$GCP_SA_KEY" | grep -q '^{'; then
          echo "$GCP_SA_KEY" > sa.json
        else
          echo "$GCP_SA_KEY" | base64 -d > sa.json
        fi

    - name: Run mailer
      run: python main.py
