name: OB screenshots + mailer (hourly IST)

on:
  # Trigger every hour from 09:00‒21:00 IST → 03:30‒15:30 UTC
  schedule:
    - cron: '30 3-15 * * *'  # Executes at 30 minutes past the hour, every hour between 03:30 and 15:30 UTC
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  mailer:
    runs-on: ubuntu-latest  # Specifies the environment for the job

    steps:
      # Checkout the repository to get access to the code
      - uses: actions/checkout@v3

      # Set up Python environment (version 3.10)
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install headless Chrome and chromedriver for automation
      - uses: browser-actions/setup-chrome@v1

      # Install the required Python dependencies from requirements.txt
      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the main script to capture screenshots and send email
      - name: Run script
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}  # Set SMTP user from GitHub secrets
          SMTP_PASS: ${{ secrets.SMTP_PASS }}  # Set SMTP password from GitHub secrets
        run: python main.py  # Execute the Python script
