name: Send Looker Report Email

on:
  schedule:
    # This will trigger the action every hour at 30 minutes past each hour from 9 AM to 9 PM IST
    - cron: '30 3 * * *'   # 9:00 AM IST
    - cron: '30 4 * * *'   # 10:00 AM IST
    - cron: '30 5 * * *'   # 11:00 AM IST
    - cron: '30 6 * * *'   # 12:00 PM IST
    - cron: '30 7 * * *'   # 1:00 PM IST
    - cron: '30 8 * * *'   # 2:00 PM IST
    - cron: '30 9 * * *'   # 3:00 PM IST
    - cron: '30 10 * * *'  # 4:00 PM IST
    - cron: '30 11 * * *'  # 5:00 PM IST
    - cron: '30 12 * * *'  # 6:00 PM IST
    - cron: '30 13 * * *'  # 7:00 PM IST
    - cron: '30 14 * * *'  # 8:00 PM IST
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest  # Runs on an Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout the code from the repository

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Use Python 3.10

      - name: Install Python dependencies
        run: pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          sudo apt-get install -y google-chrome-stable || sudo apt install -y chromium-browser
          CHROME_VERSION=$(google-chrome-stable --version | grep -oP "\d+\.\d+\.\d+\.\d+")
          wget -q https://storage.googleapis.com/chrome-for-testing-public/$CHROME_VERSION/linux64/chromedriver-linux64.zip -O chromedriver.zip
          unzip -o chromedriver.zip
          sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver

      - name: Run Looker Screenshot Emailer
        env:
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}  # Gmail username from secrets
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}  # Gmail app password from secrets
        run: python main.py  # Run your Python script to capture screenshots and send email
