name: Auto Mailer

on:
  schedule:
    - cron: '30 3-14 * * *' # Every hour from 09:30 to 20:30 IST
  workflow_dispatch: # Manual trigger option

jobs:
  mailer:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Chrome & Chromedriver
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip google-chrome-stable
        CHROME_VERSION=$(google-chrome-stable --version | grep -oP '\d+\.\d+\.\d+\.\d+')
        wget -q https://storage.googleapis.com/chrome-for-testing-public/${CHROME_VERSION}/linux64/chromedriver-linux64.zip -O /tmp/chromedriver.zip
        unzip -o /tmp/chromedriver.zip -d /tmp
        sudo mv /tmp/chromedriver-linux64/chromedriver /usr/bin/chromedriver
        sudo chmod +x /usr/bin/chromedriver

    - name: Run Screenshot Email Script
      env:
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      run: python main.py
