name: Auto Mailer

on:
  schedule:
    - cron: '30 3-14 * * *' # 09:30‑20:30 IST, hourly
  workflow_dispatch:

jobs:
  send-mail:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install deps
      run: |
        python -m pip install -r requirements.txt

    - name: Install Chrome + chromedriver
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable wget unzip
        CHROME_VERSION=$(google-chrome-stable --version | grep -oP '\d+\.\d+\.\d+\.\d+')
        wget -q https://storage.googleapis.com/chrome-for-testing-public/${CHROME_VERSION}/linux64/chromedriver-linux64.zip -O /tmp/chromedriver.zip
        unzip -o /tmp/chromedriver.zip -d /tmp
        sudo mv /tmp/chromedriver-linux64/chromedriver /usr/bin/chromedriver
        sudo chmod +x /usr/bin/chromedriver

    - name: Run script
      env:
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      run: python main.py
